version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "7900:7900"
      - "4444:4444"
    shm_size: 2gb

  meta-ai-proxy:
    image: ugofiasconaro/meta-ai-openai-proxy:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - WEBDRIVER_URL=http://selenium:4444
      - SELENIUM_HEADLESS=true
      - METAAI_USERNAME=${METAAI_USERNAME}
      - DEBUG_ENABLED=false
    depends_on:
      - selenium